name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Checkout Run
      - uses: cypress-io/github-action@v4
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
